const categories = [
  {
    name: "Fruits",
    slug: "fruits",
    description: "Fresh fruits including apples, bananas, mangoes, oranges and more.",
    icon: "🍎",
    color: "#22c55e",
    status: "active",
  },
  {
    name: "Vegetables",
    slug: "vegetables",
    description: "Fresh vegetables like tomatoes, potatoes, onions, carrots and more.",
    icon: "🥬",
    color: "#16a34a",
    status: "active",
  },
  {
    name: "Dairy",
    slug: "dairy",
    description: "Milk, paneer, butter, curd, ghee, cheese and other dairy products.",
    icon: "🥛",
    color: "#3b82f6",
    status: "active",
  },
  {
    name: "Bakery",
    slug: "bakery",
    description: "Fresh bread, cakes, biscuits, croissants, muffins and donuts.",
    icon: "🍞",
    color: "#f59e0b",
    status: "active",
  },
  {
    name: "Grains",
    slug: "grains",
    description: "Rice, wheat flour, dal varieties, sugar, salt and staples.",
    icon: "🌾",
    color: "#f97316",
    status: "active",
  },
  {
    name: "Dry Fruits",
    slug: "dryfruits",
    description: "Premium almonds, cashews, raisins, pistachios, walnuts and dates.",
    icon: "🥜",
    color: "#8b5cf6",
    status: "active",
  },
  {
    name: "Washing",
    slug: "washing",
    description: "Detergents, dish wash, floor cleaners and household cleaning items.",
    icon: "🧴",
    color: "#ec4899",
    status: "active",
  },
];

const products = [
  { name: "Apple (1 kg)", category: "fruits", price: 180, image: "src/apple.jpg", status: "active" },
  { name: "Banana (1 dozen)", category: "fruits", price: 60, image: "src/banana.jpg", status: "active" },
  { name: "Mango (1 kg)", category: "fruits", price: 250, image: "src/mangoo.jpg", status: "active" },
  { name: "Orange (1 kg)", category: "fruits", price: 120, image: "src/orange.jpg", status: "active" },
  { name: "Pomegranate (1 kg)", category: "fruits", price: 160, image: "src/pomogranade.jpg", status: "active" },
  { name: "Grapes (1 kg)", category: "fruits", price: 90, image: "src/grapes.jpg", status: "active" },
  { name: "Papaya (1 kg)", category: "fruits", price: 50, image: "src/papaya.jpg", status: "active" },
  { name: "Guava (1 kg)", category: "fruits", price: 70, image: "src/guava.jpg", status: "active" },
  { name: "Watermelon", category: "fruits", price: 40, image: "src/watermelon.jpg", status: "active" },
  { name: "Pineapple", category: "fruits", price: 80, image: "src/pineapple.jpg", status: "active" },
  { name: "Tomato (1 kg)", category: "vegetables", price: 40, image: "src/tomato.jpg", status: "active" },
  { name: "Potato (1 kg)", category: "vegetables", price: 30, image: "src/potato.jpg", status: "active" },
  { name: "Onion (1 kg)", category: "vegetables", price: 35, image: "src/onion.jpg", status: "active" },
  { name: "Carrot (1 kg)", category: "vegetables", price: 60, image: "src/carrot.jpg", status: "active" },
  { name: "Cabbage", category: "vegetables", price: 35, image: "src/cabbage.jpg", status: "active" },
  { name: "Capsicum", category: "vegetables", price: 80, image: "src/capsicum.jpg", status: "active" },
  { name: "Spinach", category: "vegetables", price: 25, image: "src/spinach.jpg", status: "active" },
  { name: "Cauliflower", category: "vegetables", price: 45, image: "src/cauliflower.jpg", status: "active" },
  { name: "Brinjal", category: "vegetables", price: 50, image: "src/brinjal.jpg", status: "active" },
  { name: "Green Peas", category: "vegetables", price: 90, image: "src/greenpeas.jpg", status: "active" },
  { name: "Amul Milk (1L)", category: "dairy", price: 58, image: "src/amulmilk.jpg", status: "active" },
  { name: "Paneer (1 kg)", category: "dairy", price: 420, image: "src/paneer.jpg", status: "active" },
  { name: "Butter", category: "dairy", price: 250, image: "src/butter.jpg", status: "active" },
  { name: "Curd", category: "dairy", price: 70, image: "src/curd.jpg", status: "active" },
  { name: "Ghee", category: "dairy", price: 600, image: "src/ghee.jpg", status: "active" },
  { name: "Cheese", category: "dairy", price: 480, image: "src/cheese.jpg", status: "active" },
  { name: "Buttermilk", category: "dairy", price: 25, image: "src/buttermilk.jpg", status: "active" },
  { name: "White Bread", category: "bakery", price: 45, image: "src/whitebread.jpg", status: "active" },
  { name: "Brown Bread", category: "bakery", price: 55, image: "src/brownbread.jpg", status: "active" },
  { name: "Cake (1kg)", category: "bakery", price: 600, image: "src/cake.jpg", status: "active" },
  { name: "Biscuits", category: "bakery", price: 30, image: "src/biscuits.jpg", status: "active" },
  { name: "Croissant", category: "bakery", price: 90, image: "src/croissant.jpg", status: "active" },
  { name: "Muffins", category: "bakery", price: 120, image: "src/muffins.jpg", status: "active" },
  { name: "Donuts", category: "bakery", price: 80, image: "src/donuts.jpg", status: "active" },
  { name: "Basmati Rice (5kg)", category: "grains", price: 450, image: "src/basmatirice.jpg", status: "active" },
  { name: "Wheat Flour (5kg)", category: "grains", price: 250, image: "src/wheatflour.jpg", status: "active" },
  { name: "Toor Dal (1kg)", category: "grains", price: 160, image: "src/toordal.jpg", status: "active" },
  { name: "Moong Dal (1kg)", category: "grains", price: 130, image: "src/moongdal.jpg", status: "active" },
  { name: "Chana Dal (1kg)", category: "grains", price: 120, image: "src/chanadal.jpg", status: "active" },
  { name: "Sugar (1kg)", category: "grains", price: 45, image: "src/sugar.jpg", status: "active" },
  { name: "Salt (1kg)", category: "grains", price: 25, image: "src/salt.jpg", status: "active" },
  { name: "Almonds (1kg)", category: "dryfruits", price: 750, image: "src/almonds.jpg", status: "active" },
  { name: "Cashews (1kg)", category: "dryfruits", price: 900, image: "src/cashews.jpg", status: "active" },
  { name: "Raisins (1kg)", category: "dryfruits", price: 350, image: "src/raisins.jpg", status: "active" },
  { name: "Pistachios (1kg)", category: "dryfruits", price: 1100, image: "src/pistachios.jpg", status: "active" },
  { name: "Walnuts (1kg)", category: "dryfruits", price: 800, image: "src/walnuts.jpg", status: "active" },
  { name: "Dates (1kg)", category: "dryfruits", price: 450, image: "src/dates.jpg", status: "active" },
  { name: "Surf Excel (1kg)", category: "washing", price: 320, image: "src/surfexcel.jpg", status: "active" },
  { name: "Ariel (1kg)", category: "washing", price: 300, image: "src/ariel.jpg", status: "active" },
  { name: "Tide (1kg)", category: "washing", price: 290, image: "src/tide.jpg", status: "active" },
  { name: "Vim Liquid (1L)", category: "washing", price: 120, image: "src/vimliquid.jpg", status: "active" },
  { name: "Harpic", category: "washing", price: 110, image: "src/harpic.jpg", status: "active" },
  { name: "Lizol", category: "washing", price: 150, image: "src/lizol.jpg", status: "active" },
];

const stores = [
  { name: "D-Mart", location: "Pan India", status: "active" },
  { name: "Reliance Fresh", location: "Pan India", status: "active" },
  { name: "JioMart", location: "Online", status: "active" },
  { name: "Big Bazaar", location: "Pan India", status: "active" },
  { name: "More Supermarket", location: "South India", status: "active" },
  { name: "Spencer's", location: "Metro Cities", status: "active" },
  { name: "Star Bazaar", location: "Mumbai, Hyderabad", status: "active" },
  { name: "Flipkart Grocery", location: "Online", status: "active" },
  { name: "Amazon Pantry", location: "Online", status: "active" },
  { name: "Metro Cash & Carry", location: "Metro Cities", status: "active" },
  { name: "Nature's Basket", location: "Mumbai, Delhi, Bangalore", status: "active" },
  { name: "Vishal Mega Mart", location: "North India", status: "active" },
  { name: "Ratnadeep", location: "Hyderabad", status: "active" },
  { name: "Heritage Fresh", location: "South India", status: "active" },
  { name: "Easyday", location: "North India", status: "inactive" },
];

module.exports = { categories, products, stores };
