const categoryImages = {
  fruits: "src/apple.jpg",
  vegetables: "src/tomato.jpg",
  dairy: "src/amulmilk.jpg",
  bakery: "src/whitebread.jpg",
  grains: "src/basmatirice.jpg",
  dryfruits: "src/almonds.jpg",
  washing: "src/surfexcel.jpg",
};

const productImages = {
  "Apple (1 kg)": "src/apple.jpg",
  "Banana (1 dozen)": "src/banana.jpg",
  "Mango (1 kg)": "src/mangoo.jpg",
  "Orange (1 kg)": "src/orange.jpg",
  "Pomegranate (1 kg)": "src/pomogranade.jpg",
  "Grapes (1 kg)": "src/grapes.jpg",
  "Papaya (1 kg)": "src/papaya.jpg",
  "Guava (1 kg)": "src/guava.jpg",
  Watermelon: "src/watermelon.jpg",
  Pineapple: "src/pineapple.jpg",
  "Tomato (1 kg)": "src/tomato.jpg",
  "Potato (1 kg)": "src/potato.jpg",
  "Onion (1 kg)": "src/onion.jpg",
  "Carrot (1 kg)": "src/carrot.jpg",
  Cabbage: "src/cabbage.jpg",
  Capsicum: "src/capsicum.jpg",
  Spinach: "src/spinach.jpg",
  Cauliflower: "src/cauliflower.jpg",
  Brinjal: "src/brinjal.jpg",
  "Green Peas": "src/greenpeas.jpg",
  "Amul Milk (1L)": "src/amulmilk.jpg",
  "Paneer (1 kg)": "src/paneer.jpg",
  Butter: "src/butter.jpg",
  Curd: "src/curd.jpg",
  Ghee: "src/ghee.jpg",
  Cheese: "src/cheese.jpg",
  Buttermilk: "src/buttermilk.jpg",
  "White Bread": "src/whitebread.jpg",
  "Brown Bread": "src/brownbread.jpg",
  "Cake (1kg)": "src/cake.jpg",
  Biscuits: "src/biscuits.jpg",
  Croissant: "src/croissant.jpg",
  Muffins: "src/muffins.jpg",
  Donuts: "src/donuts.jpg",
  "Basmati Rice (5kg)": "src/basmatirice.jpg",
  "Wheat Flour (5kg)": "src/wheatflour.jpg",
  "Toor Dal (1kg)": "src/toordal.jpg",
  "Moong Dal (1kg)": "src/moongdal.jpg",
  "Chana Dal (1kg)": "src/chanadal.jpg",
  "Sugar (1kg)": "src/sugar.jpg",
  "Salt (1kg)": "src/salt.jpg",
  "Almonds (1kg)": "src/almonds.jpg",
  "Cashews (1kg)": "src/cashews.jpg",
  "Raisins (1kg)": "src/raisins.jpg",
  "Pistachios (1kg)": "src/pistachios.jpg",
  "Walnuts (1kg)": "src/walnuts.jpg",
  "Dates (1kg)": "src/dates.jpg",
  "Surf Excel (1kg)": "src/surfexcel.jpg",
  "Ariel (1kg)": "src/ariel.jpg",
  "Tide (1kg)": "src/tide.jpg",
  "Vim Liquid (1L)": "src/vimliquid.jpg",
  Harpic: "src/harpic.jpg",
  Lizol: "src/lizol.jpg",
};

function imageForProduct(name, category) {
  return productImages[name] || categoryImages[category] || "src/apple.jpg";
}

const categories = [
  {
    name: "Fruits",
    slug: "fruits",
    description: "Fresh fruits including apples, bananas, mangoes, oranges and more.",
    icon: "🍎",
    color: "#22c55e",
    status: "active",
  },
  {
    name: "Vegetables",
    slug: "vegetables",
    description: "Fresh vegetables like tomatoes, potatoes, onions, carrots and more.",
    icon: "🥬",
    color: "#16a34a",
    status: "active",
  },
  {
    name: "Dairy",
    slug: "dairy",
    description: "Milk, paneer, butter, curd, ghee, cheese and other dairy products.",
    icon: "🥛",
    color: "#3b82f6",
    status: "active",
  },
  {
    name: "Bakery",
    slug: "bakery",
    description: "Fresh bread, cakes, biscuits, croissants, muffins and donuts.",
    icon: "🍞",
    color: "#f59e0b",
    status: "active",
  },
  {
    name: "Grains",
    slug: "grains",
    description: "Rice, wheat flour, dal varieties, sugar, salt and staples.",
    icon: "🌾",
    color: "#f97316",
    status: "active",
  },
  {
    name: "Dry Fruits",
    slug: "dryfruits",
    description: "Premium almonds, cashews, raisins, pistachios, walnuts and dates.",
    icon: "🥜",
    color: "#8b5cf6",
    status: "active",
  },
  {
    name: "Washing",
    slug: "washing",
    description: "Detergents, dish wash, floor cleaners and household cleaning items.",
    icon: "🧴",
    color: "#ec4899",
    status: "active",
  },
];

const products = [
  { name: "Apple (1 kg)", category: "fruits", price: 180, image: imageForProduct("Apple (1 kg)", "fruits"), status: "active" },
  { name: "Banana (1 dozen)", category: "fruits", price: 60, image: imageForProduct("Banana (1 dozen)", "fruits"), status: "active" },
  { name: "Mango (1 kg)", category: "fruits", price: 250, image: imageForProduct("Mango (1 kg)", "fruits"), status: "active" },
  { name: "Orange (1 kg)", category: "fruits", price: 120, image: imageForProduct("Orange (1 kg)", "fruits"), status: "active" },
  { name: "Pomegranate (1 kg)", category: "fruits", price: 160, image: imageForProduct("Pomegranate (1 kg)", "fruits"), status: "active" },
  { name: "Grapes (1 kg)", category: "fruits", price: 90, image: imageForProduct("Grapes (1 kg)", "fruits"), status: "active" },
  { name: "Papaya (1 kg)", category: "fruits", price: 50, image: imageForProduct("Papaya (1 kg)", "fruits"), status: "active" },
  { name: "Guava (1 kg)", category: "fruits", price: 70, image: imageForProduct("Guava (1 kg)", "fruits"), status: "active" },
  { name: "Watermelon", category: "fruits", price: 40, image: imageForProduct("Watermelon", "fruits"), status: "active" },
  { name: "Pineapple", category: "fruits", price: 80, image: imageForProduct("Pineapple", "fruits"), status: "active" },
  { name: "Tomato (1 kg)", category: "vegetables", price: 40, image: imageForProduct("Tomato (1 kg)", "vegetables"), status: "active" },
  { name: "Potato (1 kg)", category: "vegetables", price: 30, image: imageForProduct("Potato (1 kg)", "vegetables"), status: "active" },
  { name: "Onion (1 kg)", category: "vegetables", price: 35, image: imageForProduct("Onion (1 kg)", "vegetables"), status: "active" },
  { name: "Carrot (1 kg)", category: "vegetables", price: 60, image: imageForProduct("Carrot (1 kg)", "vegetables"), status: "active" },
  { name: "Cabbage", category: "vegetables", price: 35, image: imageForProduct("Cabbage", "vegetables"), status: "active" },
  { name: "Capsicum", category: "vegetables", price: 80, image: imageForProduct("Capsicum", "vegetables"), status: "active" },
  { name: "Spinach", category: "vegetables", price: 25, image: imageForProduct("Spinach", "vegetables"), status: "active" },
  { name: "Cauliflower", category: "vegetables", price: 45, image: imageForProduct("Cauliflower", "vegetables"), status: "active" },
  { name: "Brinjal", category: "vegetables", price: 50, image: imageForProduct("Brinjal", "vegetables"), status: "active" },
  { name: "Green Peas", category: "vegetables", price: 90, image: imageForProduct("Green Peas", "vegetables"), status: "active" },
  { name: "Amul Milk (1L)", category: "dairy", price: 58, image: imageForProduct("Amul Milk (1L)", "dairy"), status: "active" },
  { name: "Paneer (1 kg)", category: "dairy", price: 420, image: imageForProduct("Paneer (1 kg)", "dairy"), status: "active" },
  { name: "Butter", category: "dairy", price: 250, image: imageForProduct("Butter", "dairy"), status: "active" },
  { name: "Curd", category: "dairy", price: 70, image: imageForProduct("Curd", "dairy"), status: "active" },
  { name: "Ghee", category: "dairy", price: 600, image: imageForProduct("Ghee", "dairy"), status: "active" },
  { name: "Cheese", category: "dairy", price: 480, image: imageForProduct("Cheese", "dairy"), status: "active" },
  { name: "Buttermilk", category: "dairy", price: 25, image: imageForProduct("Buttermilk", "dairy"), status: "active" },
  { name: "White Bread", category: "bakery", price: 45, image: imageForProduct("White Bread", "bakery"), status: "active" },
  { name: "Brown Bread", category: "bakery", price: 55, image: imageForProduct("Brown Bread", "bakery"), status: "active" },
  { name: "Cake (1kg)", category: "bakery", price: 600, image: imageForProduct("Cake (1kg)", "bakery"), status: "active" },
  { name: "Biscuits", category: "bakery", price: 30, image: imageForProduct("Biscuits", "bakery"), status: "active" },
  { name: "Croissant", category: "bakery", price: 90, image: imageForProduct("Croissant", "bakery"), status: "active" },
  { name: "Muffins", category: "bakery", price: 120, image: imageForProduct("Muffins", "bakery"), status: "active" },
  { name: "Donuts", category: "bakery", price: 80, image: imageForProduct("Donuts", "bakery"), status: "active" },
  { name: "Basmati Rice (5kg)", category: "grains", price: 450, image: imageForProduct("Basmati Rice (5kg)", "grains"), status: "active" },
  { name: "Wheat Flour (5kg)", category: "grains", price: 250, image: imageForProduct("Wheat Flour (5kg)", "grains"), status: "active" },
  { name: "Toor Dal (1kg)", category: "grains", price: 160, image: imageForProduct("Toor Dal (1kg)", "grains"), status: "active" },
  { name: "Moong Dal (1kg)", category: "grains", price: 130, image: imageForProduct("Moong Dal (1kg)", "grains"), status: "active" },
  { name: "Chana Dal (1kg)", category: "grains", price: 120, image: imageForProduct("Chana Dal (1kg)", "grains"), status: "active" },
  { name: "Sugar (1kg)", category: "grains", price: 45, image: imageForProduct("Sugar (1kg)", "grains"), status: "active" },
  { name: "Salt (1kg)", category: "grains", price: 25, image: imageForProduct("Salt (1kg)", "grains"), status: "active" },
  { name: "Almonds (1kg)", category: "dryfruits", price: 750, image: imageForProduct("Almonds (1kg)", "dryfruits"), status: "active" },
  { name: "Cashews (1kg)", category: "dryfruits", price: 900, image: imageForProduct("Cashews (1kg)", "dryfruits"), status: "active" },
  { name: "Raisins (1kg)", category: "dryfruits", price: 350, image: imageForProduct("Raisins (1kg)", "dryfruits"), status: "active" },
  { name: "Pistachios (1kg)", category: "dryfruits", price: 1100, image: imageForProduct("Pistachios (1kg)", "dryfruits"), status: "active" },
  { name: "Walnuts (1kg)", category: "dryfruits", price: 800, image: imageForProduct("Walnuts (1kg)", "dryfruits"), status: "active" },
  { name: "Dates (1kg)", category: "dryfruits", price: 450, image: imageForProduct("Dates (1kg)", "dryfruits"), status: "active" },
  { name: "Surf Excel (1kg)", category: "washing", price: 320, image: imageForProduct("Surf Excel (1kg)", "washing"), status: "active" },
  { name: "Ariel (1kg)", category: "washing", price: 300, image: imageForProduct("Ariel (1kg)", "washing"), status: "active" },
  { name: "Tide (1kg)", category: "washing", price: 290, image: imageForProduct("Tide (1kg)", "washing"), status: "active" },
  { name: "Vim Liquid (1L)", category: "washing", price: 120, image: imageForProduct("Vim Liquid (1L)", "washing"), status: "active" },
  { name: "Harpic", category: "washing", price: 110, image: imageForProduct("Harpic", "washing"), status: "active" },
  { name: "Lizol", category: "washing", price: 150, image: imageForProduct("Lizol", "washing"), status: "active" },
];

const stores = [
  { name: "D-Mart", location: "Pan India", status: "active" },
  { name: "Reliance Fresh", location: "Pan India", status: "active" },
  { name: "JioMart", location: "Online", status: "active" },
  { name: "Big Bazaar", location: "Pan India", status: "active" },
  { name: "More Supermarket", location: "South India", status: "active" },
  { name: "Spencer's", location: "Metro Cities", status: "active" },
  { name: "Star Bazaar", location: "Mumbai, Hyderabad", status: "active" },
  { name: "Flipkart Grocery", location: "Online", status: "active" },
  { name: "Amazon Pantry", location: "Online", status: "active" },
  { name: "Metro Cash & Carry", location: "Metro Cities", status: "active" },
  { name: "Nature's Basket", location: "Mumbai, Delhi, Bangalore", status: "active" },
  { name: "Vishal Mega Mart", location: "North India", status: "active" },
  { name: "Ratnadeep", location: "Hyderabad", status: "active" },
  { name: "Heritage Fresh", location: "South India", status: "active" },
  { name: "Easyday", location: "North India", status: "active" },
  { name: "BigBasket", location: "Online", status: "active" },
];

module.exports = { categories, products, stores, productImages, categoryImages };
